export { default as Home } from './Home'
export { default as About } from './About'
export { default as Detail } from './Detail'
export { default as Tag } from './Tag'
export { default as Devlog } from './Devlog'
export { default as Lifelog } from './Lifelog'
export { default as Edit } from './Edit'
export { default as Test } from './Test'
